- name: Install python build prereqs
  apt:
    name:
      - curl
      - build-essential 
      - libncurses5-dev 
      - libgdbm-dev 
      - libnss3-dev 
      - libssl-dev 
      - libffi-dev
      - libreadline-gplv2-dev
      - libsqlite3-dev
      - tk-dev
      - libgdbm-dev
      - libc6-dev
      - libbz2-dev
      - libffi-dev
      - zlib1g-dev
