---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: debian:buster
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        python_version: 3.8.2
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  name: ansible
